### ISSUE TITLE
Plugin system to support metadata querying

### ISSUE THREAD

**Issue by ariyan-eghbal** [AmrDeveloper/FileQL#1]
A plugin system that make `FileQL` able to load parsers to extract file type specific metadata and make them available for filtering in query  seems very useful  
for example if someone can write a parser/metadata extractor plugin and add it to `FileQL` to support video/audio meta data (like length, video size, rate ...) 

Is there any plan to support such a feature?

**Comment by AmrDeveloper** [comment]
Hello @ariyan-eghbal,

Thank for your suggestion, for now i can make different tables for audio, videos ...etc,

But i will we need to support plugin system in GitQL SDk in general

Thanks,
Amr Hesham

**Comment by AmrDeveloper** [comment]
Hello @ariyan-eghbal,

Staring from GitQL 0.20.0 you can add, remove or override std functions and aggregations so we can start working on DSL for files, metadata, auto, images ...etc

https://github.com/AmrDeveloper/GQL/releases/tag/0.20.0

Thank you
